### ISSUE TITLE
pointcloud_octomap_updater Segfault with PointCloud2Iterator

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#505]
@vrabaud 

Filtering point clouds with Primesense / Asus Xtion / MoveIt! worked fine for me until I believe https://github.com/ros-planning/moveit_ros/commit/db046243ac0628ad28f2b71bde9af76f25cf54ce. Now it segfaults.

I'm listening to topic

```
/camera/depth_registered/points
```

Here is an example [rosbag recording](http://dav.ee/camera__depth_registered__points.bag)

It's header is:

```
header: 
  seq: 195611
  stamp: 
    secs: 1413582743
    nsecs: 277334231
  frame_id: /camera_rgb_optical_frame
height: 480
width: 640
fields: 
  - 
    name: x
    offset: 0
    datatype: 7
    count: 1
  - 
    name: y
    offset: 4
    datatype: 7
    count: 1
  - 
    name: z
    offset: 8
    datatype: 7
    count: 1
  - 
    name: rgb
    offset: 16
    datatype: 7
    count: 1
is_bigendian: False
point_step: 32
row_step: 20480
```

When I run move_group with point cloud filtering enabled, it crashes - [backtrace](https://gist.github.com/davetcoleman/7dfe9a4238f38c90b631) - with:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe1222700 (LWP 18779)]
0x00007fffd1abde86 in occupancy_map_monitor::PointCloudOctomapUpdater::cloudMsgCallback (this=0xb92080, cloud_msg=...) at /home/dave/ros/ws_moveit/src/moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp:244
244         if (!isnan(*iter_x) && !isnan(*iter_y) && !isnan(*iter_z))
```

I dug pretty deep into the segfault - `iter_x` is moving past its max size. On row 25 out of 480 it already suprases its bound. I suspect it is because the `row_step` is 20480. `iter_x` is set to index 512000 but the cloud_msg height*width = 307200.

I tried this very related PR https://github.com/ros-planning/moveit_ros/pull/504, and I believe it is part of the solution, but I still get the segfault.

**Comment by jasedit** [comment]
It looks like PointCloud2Iterators iterate point-at-a-time, based on reading the relevant [header](http://docs.ros.org/indigo/api/sensor_msgs/html/impl_2point__cloud2__iterator_8h_source.html). That would suggest that the iterators should not be incremented by row_step.

**Comment by jasedit** [comment]
I have a potential fix for this, but I cannot reproduce the issue with the rosbag provided. I can't publish tf's in the same time frame as the log, since it doesn't have any /clock topic. If there's a way to publish a tf with a specific timestamp, then I could validate my fix, but I have yet to figure out an easy way to do this.

**Comment by davetcoleman** [comment]
I can provide a better rosbag on Monday, but I wouldn't mind seeing your potential fix now.

**Comment by jasedit** [comment]
I've pushed the fix to my fork, which has included it in Pull Request #504.

**Comment by vrabaud** [comment]
I believe the fix is more:

```
iter_x += (row*cloud_msg->row_step) / cloud_msg->point_step;
```

**Comment by davetcoleman** [comment]
It doesn't crash anymore! But it is publishing an empty pointcloud, by that I mean all 0's:

```
header: 
  seq: 258
  stamp: 
    secs: 1413840761
    nsecs: 207251985
  frame_id: /camera_rgb_optical_frame
height: 1
width: 307200
fields: 
  - 
    name: x
    offset: 0
    datatype: 7
    count: 1
  - 
    name: y
    offset: 4
    datatype: 7
    count: 1
  - 
    name: z
    offset: 8
    datatype: 7
    count: 1
is_bigendian: False
point_step: 16
row_step: 4915200
data: [0, 0, 0, 0, 0, 0, 0, 0... 
```

**Comment by jasedit** [comment]
Does it publish all 0's using the code from #504 as well? The iteration in db04624 iterates over the filtered_cloud only - it doesn't actually process the incoming point cloud. I would expect all 0's from that code if you had a filtered_cloud_topic set, and a crash if you didn't.

**Comment by davetcoleman** [comment]
Brilliant! that worked, thanks so much @jasedit @vrabaud ~

**Comment by jasedit** [comment]
What changes should I make to #504 for this? Right now it has an attempted fix for this which is similar to the fix @vrabaud mentions above, but is slightly wrong if `row_step/point_step != width`. I can adjust my version to match, or eliminate the attempted fix altogether - just let me know.

**Comment by vrabaud** [comment]
just made https://github.com/ros-planning/moveit_ros/pull/506

**Comment by davetcoleman** [comment]
actually, it appears to be passing through all the points and not doing any filtering of my robot.

My sensors_rgbd.yaml file:

```
sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth_registered/points
    max_range: 3.0 # The max range (in m) of the sensor
    padding_offset: 0.08 #0.15  #The padding offset to be considered for robot links and attached objects when self-filtering
    padding_scale: 1 #The padding scale to be considered for robot links and attached objects when self-filtering
    point_subsample: 1 # If the update process is too slow, points could be subsampled. Values above 1 make the updated skip points instead of processing them.
    filtered_cloud_topic: filtered_cloud # If this parameter is specified, the filtered cloud (without robot parts) is also republished. This makes things a little less efficient but can be useful for debugging.
```
